### ISSUE TITLE
need fine tuned collision calculation algorithm for the birdy

### ISSUE THREAD

**Issue by bencao** [frescoraja/crappy_bird#2]
Sometimes I failed the game but I do think my birdy didn't touch the obstacle pipes.
So it's something hurt use experience :) and may explain why current high score is only like 13 or 15.

**Comment by frescoraja** [comment]
Used circle as colliding object to represent birdy instead of rectangle to give more accurate collision detection

**Comment by frescoraja** [comment]
refactored the intersection algorithm so it's a lot cleaner now.
